# Generated by Django 5.1.3 on 2024-12-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordExplanation',
            fields=[
                ('word', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('audio_file', models.CharField(blank=True, max_length=255, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
