# Generated by Django 5.1.3 on 2024-12-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_wordexplanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordexplanation',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
